# -*- coding: utf-8 -*-
"""PlutoAcademy_Project01_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-KSAsnMcoElGGdudLOWJt9GE6yvVl4r
"""

import pandas as pd
df=pd.read_csv("netflix_titles.csv")
print("dataset loaded succesfully!")
print("rows and columns:",df.shape)
df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()
print("duplicates before:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("duplicates after:", df.duplicated().sum())

"""This dataset is about Movies and TV Shows that're on Netflix. It has things like the title of the Movies and TV Shows the director, the cast, the country where they were made the year they were released the rating how long they're what category they fit into. When I looked at the dataset I saw that it has 8,807 records and 12 columns. The Netflix dataset has some spaces in some of the columns but there are no records that are exactly the same. I will look at the Netflix data some more to see what trends I can find in the Movies and TV Shows on Netflix and to find some information, about Netflix Movies and TV Shows."""

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')
df.isnull().sum()

df['date_added'] = df['date_added'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Not Rated')
df['duration'] = df['duration'].fillna('Unknown')
df.isnull().sum()

df.isnull().sum()

df.duplicated().sum()

"""Data Cleaning Decisions

Before I started analyzing the data I checked it for missing information and duplicate entries. I found values in columns like director, cast, country, date_added, rating and duration. I decided to fill the gaps with labels like "Unknown" and "Not Rated" instead of getting rid of those records. That way I did not lose any data. I also looked for entries but I did not find any. After cleaning I successfully handled all the missing values. The dataset was ready, for further analysis.
"""

df['type'].value_counts()

"""Observation(for the above code) The dataset contains more Movies than TV Shows. There are 6,131 Movies and 2,676 TV Shows are present on Netflix. Netflix has a major focus on movies compared to television shows



"""

df['country'].value_counts().head(10)

"""Observation

The United States contributes the highest number of titles on Netflix with 2,818 entries. India is the second-largest contributor with 972 titles. This indicates that Netflix relies heavily on content from the United States while also maintaining a strong presence in the Indian market.
"""

df['release_year'].value_counts().head(10)

"""Observation

The year 2018 has the highest number of titles with 1,147 releases. The years 2017 and 2019 also show a large number of content. This indicates that Netflix experienced significant growth in content production between 2017 and 2020.
"""

df['rating'].value_counts().head(10)

"""observation
 TV-MA is the most common rating on Netflix with 3,207 titles, followed by TV-14 with 2,160 titles.a large portion of Netflix content is targeted towards teenagers and mature audiences. Family-friendly ratings such as TV-Y and TV-G are available but appear less frequently in the dataset.



"""

df['listed_in'].value_counts().head(10)

"""observation The most common genre category in the dataset is "Dramas, International Movies" with 362 titles, followed closely by documentaries and Stand-Up Comedy. Netflix offers a wide variety of drama-based and international content. The popularity of documentaries also indicates growing viewer interest in educational and real-world topics



"""

import matplotlib.pyplot as plt
df['type'].value_counts().plot(kind='bar')
plt.title('movies vs tv shows on netflix')
plt.xlabel('content Type')
plt.ylabel('count')
plt.show()

"""The bar chart clearly shows that Movies are available in larger numbers than TV Shows. This indicates that Netflix focuses more on movies compared to television series.



"""

import pandas as pd
df = pd.read_csv("netflix_titles.csv")

import matplotlib.pyplot as plt
plt.scatter(df.index, df['release_year'])
plt.title('Scatter Plot of Release Years')
plt.xlabel('Record Number')
plt.ylabel('Release Year')
plt.show()

import matplotlib.pyplot as plt
df['country'].value_counts().head(10).plot(kind='bar')
plt.title('top 10 countries by netflix content')
plt.xlabel('country')
plt.ylabel('number of titles')
plt.show()

"""The United States havibg highest number of titles, while India holds the second position. This highlights the importance of these countries in Netflix's content library."""

import matplotlib.pyplot as plt
df['release_year'].value_counts().sort_index().plot(kind='line')
plt.title("netflix content released by year")
plt.xlabel('release year')
plt.ylabel('number of titles')
plt.show()

"""The number of titles released on Netflix increased significantly after 2015 and reached a peak around 2018. This indicates a period of rapid content expansion on the platform.


"""

df['rating'].value_counts().head(5).plot(
    kind='pie',autopct='%1.1f%%'
)
plt.title('Top 5 Netflix Ratings')
plt.ylabel('')
plt.show()

"""pie chart

TV-MA occupies the largest portion of the chart, showing that mature-audience content and teeneger forms a major part of Netflix's catalog.



"""

import matplotlib.pyplot as plt
df['release_year'].hist(bins=20)
plt.title("distribution of release years")
plt.xlabel('release Year')
plt.ylabel("frequency")
plt.show()

"""Chart Observation

Most titles belong to recent years, while comparatively fewer titles were released in earlier decades.



"""

import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(df.isnull(), cbar=False)
plt.title('Missing Values Heatmap')
plt.show()

"""Chart Observation

The heatmap confirms that missing values were successfully handled during the data cleaning stage, as no major gaps are visible.

The Netflix dataset has 8,807 records and 12 columns. It has information about movies and TV shows on Netflix. This dataset includes details like title,country,director,release year,rating,genre The missing values were removed during cleaning. The dataset is good for checking out the data and making visualizations about movies and TV shows on Netflix. The Netflix dataset is great for understanding what is, on Netflix.

five insights

1.Netflix have more Movies (6131) than TV Shows (2676).stonger on movie content 2.The United States is the largest content producer on Netflix with 2818 titles, followed by India with 972 titles 3.Netflix content releases peaked in 2018 with 1147 titles, showing rapid growth during that period. 4.TV-MA is the most common content rating (3207 titles), indicating a large amount of mature-audience content. 5.Drama and International Movie categories are the most common genres on Netflix, while documentaries and stand-up comedy are also highly represented.

Surprising Finding

The biggest surprise from this analysis was that 2018 had the most content releases on Netflix. I thought recent years would have releases.

Another thing that stood out was the difference between Movies and TV Shows.

These findings gave us ideas, about Netflixs content plan and how it grew over time.s, on Netflix.

I worked on a project where I looked at the Netflix dataset. I found some things about the kind of content they have when it was released how it was rated where it came from and what type of genre it was. The Netflix dataset showed me that Netflix has Movies than TV Shows. I also found out that the United States makes the content, for Netflix.
"""