# -*- coding: utf-8 -*-
"""PlutoAcademy_Project01_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-KSAsnMcoElGGdudLOWJt9GE6yvVl4r
"""

import pandas as pd
df = pd.read_csv("netflix_titles.csv")
print("Dataset Loaded Succesfully!")
print("Rows and Columns:",df.shape)
df.head()

df.info()

df.isnull().sum()

print("Duplicates before:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Duplicates after:", df.duplicated().sum())

"""The Netflix dataset contains 8,807 records and 12 columns. It includes information about movies and TV shows available on Netflix. The dataset contains details such as title, director, cast, country, release year, rating, and genre. Missing values were found in a few columns and were handled during data cleaning. No duplicate records were found in the dataset, making it suitable for exploratory data analysis and visualization."""

df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

df.isnull().sum()

df['date_added'] = df['date_added'].fillna('Unknown')
df['rating'] = df['rating'].fillna('Not Rated')
df['duration'] = df['duration'].fillna('Unknown')

df.isnull().sum()

df['type'].value_counts()

import matplotlib.pyplot as plt

df['type'].value_counts().plot(kind='bar')

plt.title('Movies vs TV Shows on Netflix')
plt.xlabel('Content Type')
plt.ylabel('Count')

plt.show()

df['country'].value_counts().head(10)

import pandas as pd

df = pd.read_csv("netflix_titles.csv")

import matplotlib.pyplot as plt

plt.scatter(df.index, df['release_year'])

plt.title('Scatter Plot of Release Years')
plt.xlabel('Record Number')
plt.ylabel('Release Year')

plt.show()

import matplotlib.pyplot as plt

df['country'].value_counts().head(10).plot(kind='bar')

plt.title('Top 10 Countries by Netflix Content')
plt.xlabel('Country')
plt.ylabel('Number of Titles')

plt.show()

df['release_year'].value_counts().head(10)

import matplotlib.pyplot as plt

df['release_year'].value_counts().sort_index().plot(kind='line')

plt.title('Netflix Content Released by Year')
plt.xlabel('Release Year')
plt.ylabel('Number of Titles')

plt.show()

df['rating'].value_counts().head(10)

df['rating'].value_counts().head(5).plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title('Top 5 Netflix Ratings')
plt.ylabel('')

plt.show()

df['listed_in'].value_counts().head(10)

import matplotlib.pyplot as plt

df['release_year'].hist(bins=20)

plt.title('Distribution of Release Years')
plt.xlabel('Release Year')
plt.ylabel('Frequency')

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(df.isnull(), cbar=False)

plt.title('Missing Values Heatmap')
plt.show()

"""The Netflix dataset contains 8,807 records and 12 columns.
It includes information about movies and TV shows available on Netflix.
The dataset contains details such as title,country,director,release year,rating,and genre.
Missing values were cleaned during preprocessing.
The dataset is suitable for exploratory data analysis and visualization.

Insight 1

Netflix contains significantly more Movies (6131) than TV Shows (2676).

Insight 2

The United States is the largest content producer on Netflix with 2818 titles, followed by India with 972 titles.

Insight 3

Netflix content releases peaked in 2018 with 1147 titles, showing rapid growth during that period.

Insight 4

TV-MA is the most common content rating (3207 titles), indicating a large amount of mature-audience content.

Insight 5

Drama and International Movie categories are the most common genres on Netflix, while documentaries and stand-up comedy are also highly represented.

### Data Cleaning Decisions

During data cleaning, I found missing values in the director, cast, country, date_added, rating, and duration columns. To avoid losing useful information, I replaced the missing values with appropriate labels such as "Unknown" and "Not Rated" instead of deleting the records. This allowed me to keep all 8,807 entries in the dataset for analysis. I also checked the dataset for duplicate records using the duplicated() function and found that there were no duplicate rows, so no records were removed. After applying these changes, I verified the dataset again and confirmed that all missing values had been handled successfully, making the data clean and ready for exploratory data analysis and visualization.

### Question 1: What is the distribution of Movies and TV Shows on Netflix?

```python
df['type'].value_counts()
```

Output:

Movie      6131
TV Show    2676

Insight:
Netflix contains more Movies than TV Shows.

### Question 2: Which countries contribute the most content to Netflix?

```python
df['country'].value_counts().head(10)
```

Output:

United States    2818
India             972
Unknown           831
United Kingdom    419
Japan             245

Insight:
The United States contributes the highest number of titles, followed by India.

### Question 3: Which release years have the highest number of titles?

```python
df['release_year'].value_counts().head(10)
```

Output:

2018    1147
2017    1032
2019    1030
2020     953
2016     902

Insight:
The highest number of Netflix titles were released in 2018.

### Question 4: What are the most common content ratings on Netflix?

```python
df['rating'].value_counts().head(10)
```

Output:

TV-MA    3207
TV-14    2160
TV-PG     863
R         799
PG-13     490

Insight:
TV-MA is the most common rating, indicating a large amount of mature content.

### Question 5: What are the most popular genres on Netflix?

```python
df['listed_in'].value_counts().head(10)
```

Output:

Dramas, International Movies                         362
Documentaries                                        359
Stand-Up Comedy                                      334
Comedies, Dramas, International Movies               274
Dramas, Independent Movies, International Movies     252

Insight:
Drama and International Movie categories are the most common genres on Netflix.

### Business / Research Insights

1. **Movies dominate Netflix content.** Based on the Movies vs TV Shows bar chart, Netflix has 6,131 Movies compared to 2,676 TV Shows. This suggests that Netflix focuses more heavily on movie content than television content.

2. **The United States is the leading content producer on Netflix.** According to the Top Countries chart, the United States contributes 2,818 titles, which is significantly higher than any other country. India is the second-largest contributor with 972 titles.

3. **Netflix content production peaked around 2018.** The Release Year line chart shows that 2018 had the highest number of titles (1,147). This indicates a period of rapid content expansion on the platform.

4. **Most Netflix content is targeted toward mature audiences.** The Ratings pie chart shows that TV-MA is the most common rating with 3,207 titles. This suggests that a large portion of Netflix content is designed for adult viewers.

5. **Drama and international content are highly popular categories.** Based on the Genre analysis, "Dramas, International Movies" is the most common category with 362 titles. This indicates strong demand for drama-based and globally produced content on Netflix.
"""